resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- secrets.yaml
- ingress.yaml
commonLabels:
  app: openeuler-ccs
namespace: openeuler-ccs
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/ccs-eureka
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/ccs-eureka
  newTag: "1612346456"
