---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  namespace: openeuler-ccs
spec:
  clusterIP: None
  ports:
    - name: 
      port: 80
      targetPort: 9761
  selector:
    app: ccs-eureka
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-nodeport
  namespace: openeuler-ccs
spec:
  type: NodePort
  ports:
  - name: server
    port: 80
    targetPort: 9761
    nodePort: 31011
  selector:
    app: ccs-eureka
---
apiVersion: v1
kind: Service
metadata:
  name: openeuler-ccs-config-service
  namespace: openeuler-ccs
spec:
  clusterIP: None
  ports:
    - name:
      port: 80
      targetPort: 8087
  selector:
    app: ccs-config
---
apiVersion: v1
kind: Service
metadata:
  name: openeuler-ccs-gateway-service
  namespace: openeuler-ccs
spec:
  clusterIP: None
  ports:
    - name:
      port: 80
      targetPort: 8088
  selector:
    app: ccs-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: openeuler-ccs-service
  namespace: openeuler-ccs
spec:
  ports:
    - name: openeuler-ccs
      port: 80
      protocol: TCP
      targetPort: 8086
  selector:
    app: ccs-server
  type: ClusterIP
