resources:
  - https://github.com/opensourceways/infra-openeuler/applications/openlookeng-website-frontend?ref=master
  - ingress.yaml
replicas:
- name: openlookeng-website-frontend
  count: 1
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: openlookeng-website
namespace: openlookeng-website-frontend
