resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- purge-cache.yaml
- purge-secrets.yaml
commonLabels:
  app: openlookeng-website-frontend
namespace: openlookeng-website-frontend
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openlookeng_website
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openlookeng_website
  newTag: 0ad88d5952cd4d49758e8e3d31520c0b20f1080a
