resources:
- https://github.com/opensourceways/app-bugzilla/deploy?ref=main
- ingress.yaml
commonLabels:
  app: bugzilla
namespace: bugzilla
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/bugzilla
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/bugzilla
  newTag: eec9c1a1a7b6ad01e99f4a698c0804f10a791de4.1612059550
