resources:
- https://github.com/opensourceways/app-bugzilla/deploy?ref=master
- ingress.yaml
commonLabels:
  app: bugzilla
namespace: bugzilla
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opensourceway/patchtracking
  newName: opensourceway/bugzilla
  newTag: b09210fdee6c748ebd2bff319a4fe71356da7031.1611886346
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/bugzilla
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/bugzilla
  newTag: b09210fdee6c748ebd2bff319a4fe71356da7031.1611889639
