kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- namespace.yaml
- deployment.yaml
- pvc.yaml
- service.yaml
- secrets.yaml
- configmap.yaml
commonLabels:
  label: mirrorbits
namespace: repo-mirrorbits
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/repo-mirrorbits
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/repo-mirrorbits
  newTag: 54931ce78e33c27822cd4be33e63fc8299c22c5f
