apiVersion: v1
kind: Service
metadata:
  name: repo-mirrorbits-service
  namespace: repo-mirrorbits
spec:
  ports:
    - name: repo-mirrorbits-service
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: repo-mirrorbits
  type: ClusterIP
