apiVersion: v1
kind: Service
metadata:
  # jenkins is configured with EIP in case of low visit speed if we visit this web via jenkins.openeuler.org
  name: jenkins
  annotations:
    #kubernetes.io/elb.class: union
    #kubernetes.io/elb.id: 2c584f78-38f9-4197-abc4-50d1d63dc746
    #kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
spec:
  loadBalancerIP: 119.3.233.150
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: slavelistener
      port: 50000
      targetPort: 50000
  externalTrafficPolicy: Cluster
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-agent
spec:
  ports:
    - name: http
      port: 80
      # we need pin the node port here in order to be visitable via node
      targetPort: 8080
      nodePort: 30080
    - name: slavelistener
      port: 50000
      # we need pin the node port here in order to be visitable via node
      nodePort: 30050
      targetPort: 50000
  type: NodePort
