resources:
- https://github.com/opensourceways/app-pkgmanage/deploy?ref=master
- ingress.yaml
commonLabels:
  app: openeuler-packagemanage-release
namespace: packagemanage-release
nameSuffix: -release
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opensourceway/dbgetinit
  newName: opensourceway/dbgetinit
  newTag: f8ae2da6f7bd6b3230c308b2994fea7cd89468d6.1618197291
- name: opensourceway/packagemanage
  newName: opensourceway/packagemanage
  newTag: f8ae2da6f7bd6b3230c308b2994fea7cd89468d6.1618197291
- name: opensourceway/pkgmanageweb
  newName: opensourceway/pkgmanageweb
  newTag: deb3ca987f17f858473afc3e61dfd12229cbaa91.1618197663
