resources:
- https://github.com/opensourceways/app-pkgmanage/deploy?ref=master
- ingress.yaml
commonLabels:
  app: openeuler-packagemanage-release
namespace: packagemanage-release
nameSuffix: -release
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opensourceway/dbgetinit
  newName: opensourceway/dbgetinit
  newTag: d3508837b3ca13af7d395df7a794814af90a8f9e.1618210290
- name: opensourceway/packagemanage
  newName: opensourceway/packagemanage
  newTag: d3508837b3ca13af7d395df7a794814af90a8f9e.1618210290
- name: opensourceway/pkgmanageweb
  newName: opensourceway/pkgmanageweb
  newTag: deb3ca987f17f858473afc3e61dfd12229cbaa91.1618197663
