resources:
  - ingress.yaml
  - www-ingress.yaml
  - namespace.yaml
  - cibot-service.yaml
  - cache-ingress.yaml
  - openlookeng-website-frontend-service.yaml
commonLabels:
  app: openlookeng-website
patchesJson6902:
  - target:
      group: ""
      version: v1
      kind: Service
      name: openlookeng-website-frontend-service
    path: selector.yaml
  - target:
      group: ""
      version: v1
      kind: Service
      name: openlookeng-bot-internal
    path: selector.yaml
