resources:
- https://github.com/opensourceways/app-pkgmanage/deploy?ref=debug
- ingress.yaml
commonLabels:
  app: openeuler-packagemanage-debug
nameSuffix: -debug
namespace: packagemanage-debug
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opensourceway/dbgetinit
  newName: opensourceway/dbgetinit
  newTag: 43774888793b1cf8e6c859e9aad29c4418b91ae0.1615536579
- name: opensourceway/packagemanage
  newName: opensourceway/packagemanage
  newTag: 43774888793b1cf8e6c859e9aad29c4418b91ae0.1615536579
- name: opensourceway/pkgmanageweb
  newName: opensourceway/pkgmanageweb
  newTag: d62191e2cc5e6ddfa82a6f9adb92a84900e9bace.1615531653
