resources:
- https://github.com/opensourceways/app-pkgmanage/deploy?ref=debug
- ingress.yaml
commonLabels:
  app: openeuler-packagemanage-debug
nameSuffix: -debug
namespace: packagemanage-debug
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opensourceway/dbgetinit
  newName: opensourceway/dbgetinit
  newTag: 506db81ed9665418dc1bc1b5a5cfc67521872e5e.1616489354
- name: opensourceway/packagemanage
  newName: opensourceway/packagemanage
  newTag: 506db81ed9665418dc1bc1b5a5cfc67521872e5e.1616489354
- name: opensourceway/pkgmanageweb
  newName: opensourceway/pkgmanageweb
  newTag: 997baeb8121293566176454df01914a93e527562.1619594895
