resources:
- https://github.com/opensourceways/app-pkgmanage/deploy?ref=debug
- ingress.yaml
commonLabels:
  app: openeuler-packagemanage-debug
nameSuffix: -debug
namespace: packagemanage-debug
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opensourceway/dbgetinit
  newName: opensourceway/dbgetinit
  newTag: dfbc303a32c1543cd44d6ae02b47eed6941e09cb.1616380298
- name: opensourceway/packagemanage
  newName: opensourceway/packagemanage
  newTag: dfbc303a32c1543cd44d6ae02b47eed6941e09cb.1616380298
- name: opensourceway/pkgmanageweb
  newName: opensourceway/pkgmanageweb
  newTag: d62191e2cc5e6ddfa82a6f9adb92a84900e9bace.1615539939
