resources:
- https://github.com/opensourceways/app-pkgmanage/deploy?ref=debug
- ingress.yaml
commonLabels:
  app: openeuler-packagemanage-debug
nameSuffix: -debug
namespace: packagemanage-debug
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opensourceway/dbgetinit
  newName: opensourceway/dbgetinit
  newTag: 506db81ed9665418dc1bc1b5a5cfc67521872e5e.1616489354
- name: opensourceway/packagemanage
  newName: opensourceway/packagemanage
  newTag: 506db81ed9665418dc1bc1b5a5cfc67521872e5e.1616489354
- name: opensourceway/pkgmanageweb
  newName: opensourceway/pkgmanageweb
  newTag: d179f51435ceb6c09b5ddaa1063c76a07b03d08e.1617761894
