resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
commonLabels:
  name: website-docs
namespace: website-docs
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openeuler-website-docs
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openeuler-website-docs
  newTag: 9077154ff33a8b0821b0e0148f85acc1f0fe8faf1618366471
