apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-issuer
  name: jenkins-ingress
spec:
  tls:
    - hosts:
        - ci.kunpeng.huawei.com
      secretName: jenkins-kunpeng-tls
  rules:
    - host: ci.kunpeng.huawei.com
      http:
        paths:
          - backend:
              serviceName: jenkins
              servicePort: 80
            path: /
