apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: cve-manager
  name: cve-manager
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cve-manager
  template:
    metadata:
      labels:
        app: cve-manager
    spec:
      containers:
        - env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cve-secrets
                  key: db-username
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: cve-secrets
                  key: db-passwd
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: cve-secrets
                  key: db-uri
            - name: AES_KEY
              valueFrom:
                secretKeyRef:
                  name: cve-secrets
                  key: aes-key
            - name: HOOK_PWD
              valueFrom:
                secretKeyRef:
                  name: cve-secrets
                  key: hook-pwd
            - name: GITEE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cve-secrets
                  key: gitee-token
            - name: EMAIL_NAME
              valueFrom:
                secretKeyRef:
                  name: cve-secrets
                  key: cve-email-sendaddr
            - name: EMAIL_PWD
              valueFrom:
                secretKeyRef:
                  name: cve-secrets
                  key: cve-email-password
            - name: GITEE_GAUSS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cve-secrets
                  key: gitee_gauss_token
            - name: GITEE_MINDSPORE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cve-secrets
                  key: gitee_mindspore_token
            - name: TZ
              value: Asia/Shanghai
          image: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/cve-manager:127b0e4b9943351a7ffb19d753856e6c735d92ac
          imagePullPolicy: IfNotPresent
          name: cve-manager
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
