resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- secrets.yaml
commonLabels:
  app: hdc-task-manager
namespace: hdc-task-manager
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/hdc-task-manager
  newTag: c838dc5dbf3ec4dab36c5f57483fee0a455916f4
